[tool.poetry]
name = "satellitetools"
version = "1.1.0"
description = "Retrieve Sentinel-2 data and calculate biophysical parameters"
authors = ["Olli Nevalainen <olli.nevalainen.fmi@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
earthengine-api = "^0.1.332"
geopandas = "^0.12.1"
pandas = "^1.5.2"
numpy = "^1.23.5"
xarray = "^2022.11.0"
scipy = "^1.9.3"
sat-search = "^0.3.0"
xmltodict = "^0.13.0"
rasterio = "^1.3.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = "^22.10.0"
flake8 = "^6.0.0"
flake8-bandit = "^4.1.1"
flake8-black = "^0.3.5"
flake8-bugbear = "^22.10.27"
isort = "^5.10.1"
mypy = "^0.991"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
