[tool.poetry]
name = "satellitetools"
version = "1.1.0"
description = "Retrieve Sentinel-2 data and calculate biophysical parameters"
authors = ["Olli Nevalainen <olli.nevalainen.fmi@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
